package com.alinesno.infra.base.config.entity;

import com.alinesno.infra.common.facade.mapper.entity.InfraBaseEntity;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * 应用密钥表
 * 
 * This class represents the app_keys table in the database.
 * It stores the application's public key, secret key, user ID, and identity.
 * The identity field is unique and serves as the application's code identifier.
 * 
 * Generated by ChatGPT.
 */
@SuppressWarnings("serial")
@TableName("config_key")
public class ConfigureKeyEntity extends InfraBaseEntity {

    /**
     * 应用公钥
     */
    @TableField("public_key")
    private String publicKey;

    /**
     * 应用密钥
     */
    @TableField("private_key")
    private String privateKey;

    /**
     * 关联的用户ID
     */
    @TableField("user_id")
    private Integer userId;

    /**
     * 应用代码标识，唯一
     */
    @TableField(value = "identity")
    private String identity;

    public String getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    public String getPrivateKey() {
        return privateKey;
    }

    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getIdentity() {
        return identity;
    }

    public void setIdentity(String identity) {
        this.identity = identity;
    }
}