#spring:
#  application:
#    name: demo-config-simples

alinesno:
  configure:
    identity: 1810204389017624576
    env: dev
    enabled: true
    remote-first: true
    host: http://localhost:30102